#!/usr/bin/awk -f
BEGIN {
	if (file == "") {
		print "e.g."
		print "find . -name '*' -not -name '.git' | sed -E 's:\\./|^\\.$::g' | grep . | diff-filter -v file=<(git ls-files)"
		exit 1
	}
	DATA="|";
	CAT = "cat " file;
	while ((CAT | getline) > 0) {
		filter[$0]++
	}
	close(CAT);
}
{
	if (filter[$0]) {
		print "\033[0;34m" " " $0 "\033[0m"
	} else {
		print "\033[0;31m" "-" $0 "\033[0m"
	}
}
